abderrahim_sylius_upsell_shop_offer:
    path: /upsell/offer/{orderToken}
    defaults:
        _controller: Abderrahim\SyliusUpsellPlugin\Controller\Shop\PostPurchaseController::offerAction
    methods: [GET]
