abderrahim_sylius_upsell_shop_impression:
    path: /upsell/impression
    defaults:
        _controller: Abderrahim\SyliusUpsellPlugin\Controller\Shop\ImpressionController::recordAction
    methods: [POST]

abderrahim_sylius_upsell_shop_offer:
    path: /upsell/offer/{orderId}
    defaults:
        _controller: Abderrahim\SyliusUpsellPlugin\Controller\Shop\PostPurchaseController::offerAction
    methods: [GET]
    requirements:
        orderId: \d+

abderrahim_sylius_upsell_shop_accept:
    path: /upsell/accept/{offerId}
    defaults:
        _controller: Abderrahim\SyliusUpsellPlugin\Controller\Shop\PostPurchaseController::acceptAction
    methods: [POST]
    requirements:
        offerId: \d+

abderrahim_sylius_upsell_shop_decline:
    path: /upsell/decline
    defaults:
        _controller: Abderrahim\SyliusUpsellPlugin\Controller\Shop\PostPurchaseController::declineAction
    methods: [POST]
