services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Abderrahim\SyliusUpsellPlugin\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/DependencyInjection/'
            - '../src/SyliusUpsellPlugin.php'

    Abderrahim\SyliusUpsellPlugin\Repository\UpsellRelationRepository: ~

    Abderrahim\SyliusUpsellPlugin\Service\UpsellConfigurationProvider: ~

    Abderrahim\SyliusUpsellPlugin\Service\FrequentlyBoughtTogetherResolver:
        arguments:
            $cache: '@cache.app'

    Abderrahim\SyliusUpsellPlugin\Twig\UpsellExtension:
        tags: ['twig.extension']

    Abderrahim\SyliusUpsellPlugin\EventListener\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    Abderrahim\SyliusUpsellPlugin\EventListener\ProductFormListener: ~

    Abderrahim\SyliusUpsellPlugin\Controller\Admin\UpsellConfigurationController:
        public: true
