sylius_grid:
    grids:
        upsell_admin_upsell_offer:
            driver:
                name: doctrine/orm
                options:
                    class: '%upsell.model.offer.class%'
                    repository:
                        method: createQueryBuilder
                        arguments: ['o']
            sorting:
                priority: desc
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: ~
                triggerProduct:
                    type: twig
                    label: upsell.ui.trigger_product
                    options:
                        template: '@SyliusUpsellPlugin/Admin/upsell_offer/grid/field/product.html.twig'
                        vars:
                            field: triggerProduct
                offerProduct:
                    type: twig
                    label: upsell.ui.offer_product
                    options:
                        template: '@SyliusUpsellPlugin/Admin/upsell_offer/grid/field/product.html.twig'
                        vars:
                            field: offerProduct
                discountPercent:
                    type: string
                    label: upsell.ui.discount
                    sortable: ~
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: '@SyliusUi/grid/field/enabled.html.twig'
                priority:
                    type: string
                    label: sylius.ui.priority
                    sortable: ~
            filters:
                name:
                    type: string
                    label: sylius.ui.name
                enabled:
                    type: boolean
                    label: sylius.ui.enabled
            actions:
                main:
                    create:
                        type: create
                        label: upsell.ui.create_offer
                        options:
                            link:
                                route: upsell_admin_offer_create
                item:
                    update:
                        type: update
                        options:
                            link:
                                route: upsell_admin_offer_update
                                parameters:
                                    id: resource.id
                    delete:
                        type: delete
